import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Palette ───────────────────────────────────────────────────────────
// Exported so generateReportWord.js can reuse the identical brand/RAG colours
// rather than redefining them — same navy/RAG values as the PDF and brand kit.
export const NAVY   = [27,  54,  93]
export const WHITE  = [255, 255, 255]
export const DARK   = [30,  41,  59]
export const MID    = [100, 116, 139]
export const GREEN  = [37,  122, 59]
export const AMBER  = [212, 117, 26]
export const RED    = [220, 38,  38]
export const GREY   = [248, 250, 252]
export const LTGREY = [226, 232, 240]

// Portrait A4 layout constants
const ML    = 14
const CW    = 182
const MAX_Y = 277

// ── Domain identity colours ───────────────────────────────────────────
const DOMAIN_COLOUR_KEYS = {
  SEND:       '#4338CA',
  Equity:     '#7A5C13',
  Attendance: '#0E6251',
  Enrichment: '#6B21A8',
  Belonging:  '#334E68',
  Wellbeing:  '#5B3A9C',
}
export function domainColour(name = '') {
  for (const [key, col] of Object.entries(DOMAIN_COLOUR_KEYS)) {
    if (name.includes(key)) return col
  }
  return '#64748b'
}
export function hexToRgb(hex) {
  const h = (hex || '#94a3b8').replace('#', '')
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)]
}

export const DFE_PRINCIPLES = [
  'Leadership & Governance',
  'Early & Evidence-Based Support',
  'High Quality Adaptive Teaching',
  'Enriching Provision',
  'Safe & Respectful Culture',
  'Family & Wider Partnerships',
  'Accessible & Inclusive Environments',
]

// Relocated here (was Section 4 — Funding & Cost, removed in the Report Builder rebuild)
// because generateInclusionStrategyDraft's priority list still reads it.
export const FUNDING_LABELS = {
  pupil_premium:             'Pupil Premium',
  send_budget:               'SEND Budget',
  inclusive_mainstream_fund: 'Inclusive Mainstream Fund',
  sport_premium:             'Sport Premium',
  school_general_budget:     'General Budget',
}

// ── Helpers ───────────────────────────────────────────────────────────
export function fmt() {
  return new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}
export function academicYear() {
  const now = new Date(), y = now.getFullYear(), m = now.getMonth() // 0-indexed, Sep = 8
  return m >= 8 ? `${y}/${String(y + 1).slice(2)}` : `${y - 1}/${String(y).slice(2)}`
}
export function statusLabel(s) {
  if (s === 'in_place')    return 'In Place'
  if (s === 'in_progress') return 'In Progress'
  return 'Not In Place'
}
function checkNewPage(doc, y, needed = 20) {
  if (y + needed > MAX_Y) { doc.addPage(); return 14 }
  return y
}

// Full-width navy section bar with white text
function sectionBar(doc, y, label) {
  doc.setFillColor(...NAVY)
  doc.rect(0, y, 210, 8, 'F')
  doc.setTextColor(...WHITE)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(label.toUpperCase(), ML, y + 5.5)
  return y + 8
}

// Per-page headers and footers — skips cover page (page 1)
function applyHeadersFooters(doc, schoolName, subtitle) {
  const n = doc.getNumberOfPages()
  for (let i = 1; i <= n; i++) {
    doc.setPage(i)
    if (i === 1) continue
    doc.setFillColor(...NAVY)
    doc.rect(0, 0, 210, 10, 'F')
    doc.setTextColor(...WHITE)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text(schoolName, ML, 6.5)
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, 196, 6.5, { align: 'right' })
    doc.setFillColor(...NAVY)
    doc.rect(0, 287, 210, 10, 'F')
    doc.setTextColor(...WHITE)
    doc.setFontSize(7)
    doc.text('Inclusion Dashboard · inclusiondashboard.co.uk', ML, 293)
    doc.text(`Page ${i} of ${n}`, 196, 293, { align: 'right' })
  }
}

// ─────────────────────────────────────────────────────────────────────
// COVER PAGE
// ─────────────────────────────────────────────────────────────────────
// Simplified per the Report Builder rebuild — title is just the school name and date now;
// the old purpose/domain/group filter-summary pill row no longer applies (see TASKS.md).
function drawCoverPage(doc, { schoolName, userProfile, dateStr }) {
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, 210, 297, 'F')

  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(schoolName || 'School', 105, 128, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.setTextColor(200, 215, 235)
  doc.text(dateStr, 105, 144, { align: 'center' })

  if (userProfile?.first_name) {
    const name = [userProfile.first_name, userProfile.last_name].filter(Boolean).join(' ')
    const prepLine = userProfile.job_title ? `${name}, ${userProfile.job_title}` : name
    doc.setFontSize(8.5)
    doc.setTextColor(180, 200, 220)
    doc.text(`Prepared by: ${prepLine}`, 105, 164, { align: 'center' })
  }

  doc.setFontSize(8)
  doc.setTextColor(120, 150, 180)
  doc.text('Generated by Inclusion Dashboard · inclusiondashboard.co.uk', 105, 285, { align: 'center' })
}

// ─────────────────────────────────────────────────────────────────────
// SECTION — Inclusion Team
// ─────────────────────────────────────────────────────────────────────
// team: [{ id, role, name, chip }] — chip is one of 'approved' | 'awaiting_approval' |
// 'in_progress' | 'not_in_place' | 'not_started', built by the caller (ReportBuilder).
// Colours match the fixed status palette used everywhere else in the app; 'awaiting_approval'
// reuses the app's existing pending-approval purple (see the "Pending Approval" badge).
export const TEAM_CHIP_LABEL = {
  approved:          'Approved',
  awaiting_approval: 'Awaiting approval',
  in_progress:       'In progress',
  not_in_place:      'Not in place',
  not_started:       'Not started',
}
const TEAM_CHIP_COLOUR = {
  approved:          [47, 133, 90],
  awaiting_approval: [124, 88, 237],
  in_progress:       [217, 154, 27],
  not_in_place:      [192, 57, 43],
  not_started:       [184, 190, 199],
}

function drawInclusionTeam(doc, y, { team }) {
  y = checkNewPage(doc, y, 20)
  y = sectionBar(doc, y, 'Inclusion Team')
  y += 4

  if (!team || team.length === 0) {
    doc.setTextColor(...MID)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('None.', ML, y + 5)
    return y + 14
  }

  const body = team.map(t => [t.role, t.name || 'Not recorded', TEAM_CHIP_LABEL[t.chip] ?? t.chip])

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: ML, top: 14, bottom: 12 },
    head: [['Role', 'Name', 'Status']],
    body,
    styles:            { font: 'helvetica', fontSize: 8, cellPadding: 2.5 },
    headStyles:        { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles:{ fillColor: GREY },
    columnStyles: {
      0: { cellWidth: 62 },
      1: { cellWidth: 70 },
      2: { cellWidth: 50 },
    },
    didParseCell(data) {
      if (data.section !== 'body' || data.column.index !== 2) return
      const t = team[data.row.index]
      if (!t) return
      data.cell.styles.fontStyle = 'bold'
      data.cell.styles.textColor = TEAM_CHIP_COLOUR[t.chip] ?? MID
    },
  })
  return doc.lastAutoTable.finalY + 4
}

// ─────────────────────────────────────────────────────────────────────
// SECTION — Progress by (DfE Principle / Domain / Category)
// ─────────────────────────────────────────────────────────────────────
// Each group is { key, name, counts } where counts = computeCounts()'s
// { inPlace, inProgress, notInPlace, notStarted, total } — built by the caller
// (ReportBuilder) over the exact same points/statuses the homepage ledger counts over,
// so these numbers can never drift from the homepage's. A total of 0 draws a single grey
// "no data" bar rather than an empty one.
const NOT_STARTED_COLOUR = [184, 190, 199]

function drawProgressBar(doc, y, group) {
  const { counts } = group
  const barX = ML, barW = CW - 2, barH = 5
  const pctInPlace = counts.total ? Math.round((counts.inPlace / counts.total) * 100) : 0

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(group.name, ML, y)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MID)
  doc.text(counts.total ? `${pctInPlace}% in place` : 'No data', ML + CW, y, { align: 'right' })
  y += 3

  if (counts.total === 0) {
    doc.setFillColor(...NOT_STARTED_COLOUR)
    doc.rect(barX, y, barW, barH, 'F')
    y += barH + 5
    return y
  }

  // Ordered in place -> in progress -> not in place -> not started; zero-count segments
  // are skipped entirely rather than drawn as a sliver.
  const segments = [
    { count: counts.inPlace,    colour: GREEN },
    { count: counts.inProgress, colour: AMBER },
    { count: counts.notInPlace, colour: RED },
    { count: counts.notStarted, colour: NOT_STARTED_COLOUR },
  ]
  let x = barX
  for (const seg of segments) {
    if (seg.count <= 0) continue
    const w = (seg.count / counts.total) * barW
    doc.setFillColor(...seg.colour)
    doc.rect(x, y, w, barH, 'F')
    x += w
  }
  y += barH + 5
  return y
}

function drawProgressLegend(doc, y) {
  const legend = [['In place', GREEN], ['In progress', AMBER], ['Not in place', RED], ['Not started', NOT_STARTED_COLOUR]]
  let lx = ML
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  for (const [label, colour] of legend) {
    doc.setFillColor(...colour)
    doc.rect(lx, y - 2.5, 3, 3, 'F')
    doc.setTextColor(...MID)
    doc.text(label, lx + 4.5, y)
    lx += doc.getTextWidth(label) + 14
  }
  return y + 6
}

function drawProgressTable(doc, y, groups) {
  const body = groups.map(g => [
    g.name, g.counts.inPlace, g.counts.inProgress, g.counts.notInPlace, g.counts.notStarted, g.counts.total,
  ])
  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: ML, top: 14, bottom: 12 },
    head: [['', 'In Place', 'In Progress', 'Not In Place', 'Not Started', 'Total']],
    body,
    styles:            { font: 'helvetica', fontSize: 8, cellPadding: 2.5 },
    headStyles:        { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles:{ fillColor: GREY },
    columnStyles: {
      0: { cellWidth: 62 },
      1: { cellWidth: 24, halign: 'center' },
      2: { cellWidth: 26, halign: 'center' },
      3: { cellWidth: 26, halign: 'center' },
      4: { cellWidth: 24, halign: 'center' },
      5: { cellWidth: 20, halign: 'center' },
    },
    didParseCell(data) {
      if (data.section !== 'body') return
      if (data.column.index === 1) { data.cell.styles.textColor = GREEN; data.cell.styles.fontStyle = 'bold' }
      if (data.column.index === 2) { data.cell.styles.textColor = AMBER; data.cell.styles.fontStyle = 'bold' }
      if (data.column.index === 3) { data.cell.styles.textColor = RED;   data.cell.styles.fontStyle = 'bold' }
    },
  })
  return doc.lastAutoTable.finalY + 4
}

// section: { title, groups, showAs }. `groups`'s first row is always "All points"
// (the homepage's own overall total) — this is where the old standalone Domain Readiness
// section's overall % now lives, per the brief.
function drawProgressSection(doc, y, section) {
  const { title, groups, showAs } = section
  y = checkNewPage(doc, y, 30)
  y = sectionBar(doc, y, title)
  y += 5

  if (!groups || groups.length === 0) {
    doc.setTextColor(...MID)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('None.', ML, y + 5)
    return y + 14
  }

  if (showAs === 'chart' || showAs === 'both') {
    for (const g of groups) {
      y = checkNewPage(doc, y, 12)
      y = drawProgressBar(doc, y, g)
    }
    y = checkNewPage(doc, y, 8)
    y = drawProgressLegend(doc, y)
  }

  if (showAs === 'table' || showAs === 'both') {
    y = checkNewPage(doc, y, 20)
    y = drawProgressTable(doc, y, groups)
  }

  return y
}

// ─────────────────────────────────────────────────────────────────────
// SECTION — Barriers
// ─────────────────────────────────────────────────────────────────────
// barrierRows: the FINAL resolved list to print — None/All/Choose already applied by the
// caller — each shaped { description, whereItSits, status, actions } using
// src/utils/barrierTags.js's tags(), so the generators never re-derive tags themselves.
const BARRIER_STATUS_LABEL  = { active: 'Active', being_addressed: 'Being addressed', resolved: 'Resolved' }
const BARRIER_STATUS_COLOUR = { active: RED, being_addressed: AMBER, resolved: GREEN }

function drawBarriers(doc, y, { barrierRows }) {
  y = checkNewPage(doc, y, 30)
  y = sectionBar(doc, y, 'Barriers')
  y += 4

  if (!barrierRows || barrierRows.length === 0) {
    doc.setTextColor(...MID)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('None.', ML, y + 5)
    return y + 14
  }

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: ML, top: 14, bottom: 12 },
    head: [['Barrier', 'Where it sits', 'Status', 'Actions so far']],
    body: barrierRows.map(r => [
      r.description, r.whereItSits, BARRIER_STATUS_LABEL[r.status] ?? (r.status ?? '—'), r.actions || '—',
    ]),
    styles:            { font: 'helvetica', fontSize: 7.5, cellPadding: 2.5, overflow: 'linebreak' },
    headStyles:        { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles:{ fillColor: GREY },
    columnStyles: {
      0: { cellWidth: 48 },
      1: { cellWidth: 46 },
      2: { cellWidth: 28 },
      3: { cellWidth: 60 },
    },
    didParseCell(data) {
      if (data.section !== 'body' || data.column.index !== 2) return
      const r = barrierRows[data.row.index]
      if (!r) return
      data.cell.styles.fontStyle = 'bold'
      data.cell.styles.textColor = BARRIER_STATUS_COLOUR[r.status] ?? MID
    },
  })
  return doc.lastAutoTable.finalY + 4
}

// ─────────────────────────────────────────────────────────────────────
// SECTION — Due for review
// ─────────────────────────────────────────────────────────────────────
// reviewRows: shaped { point, whereItSits, statusText, dueLabel, isOverdue } by the caller
// from the SAME 60-day rows as the homepage's "Coming up for review" box — see
// src/utils/dueForReview.js.
function drawDueForReview(doc, y, { reviewRows }) {
  y = checkNewPage(doc, y, 30)
  y = sectionBar(doc, y, 'Due for Review')
  y += 4

  if (!reviewRows || reviewRows.length === 0) {
    doc.setTextColor(...MID)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('None.', ML, y + 5)
    return y + 14
  }

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: ML, top: 14, bottom: 12 },
    head: [['Point', 'Where it sits', 'Status', 'Due']],
    body: reviewRows.map(r => [r.point, r.whereItSits, r.statusText, r.dueLabel]),
    styles:            { font: 'helvetica', fontSize: 7.5, cellPadding: 2.5, overflow: 'linebreak' },
    headStyles:        { fillColor: NAVY, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles:{ fillColor: GREY },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 56 },
      2: { cellWidth: 30 },
      3: { cellWidth: 36 },
    },
    didParseCell(data) {
      if (data.section !== 'body' || data.column.index !== 3) return
      const r = reviewRows[data.row.index]
      if (r?.isOverdue) { data.cell.styles.fontStyle = 'bold'; data.cell.styles.textColor = RED }
    },
  })
  return doc.lastAutoTable.finalY + 4
}

// ─────────────────────────────────────────────────────────────────────
// PUBLIC API — Report Builder's four-choice evidence report
// ─────────────────────────────────────────────────────────────────────
// team, progressSections, barrierRows and reviewRows are all pre-built by ReportBuilder
// (see App.jsx) so this file stays a pure drawing layer — no filtering/aggregation logic
// of its own, matching how generateReportWord.js will consume the same shapes.
export function generateEvidenceReport({
  schoolName      = '',
  userProfile     = null,
  team            = [],
  progressSections = [],
  barrierRows     = [],
  reviewRows      = [],
}) {
  const doc      = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const dateStr  = fmt()
  const safeName = (schoolName || 'School').replace(/[^a-z0-9]/gi, '_')

  drawCoverPage(doc, { schoolName, userProfile, dateStr })

  doc.addPage()
  let y = 14

  y = drawInclusionTeam(doc, y, { team })

  for (const section of progressSections) {
    y = drawProgressSection(doc, y, section)
  }

  y = drawBarriers(doc, y, { barrierRows })
  y = drawDueForReview(doc, y, { reviewRows })

  applyHeadersFooters(doc, schoolName || 'School', `Inclusion Report — ${dateStr}`)

  doc.save(`Inclusion_Report_${safeName}_${dateStr.replace(/ /g, '_')}.pdf`)
}

// ─────────────────────────────────────────────────────────────────────
// generateInclusionStrategyDraft — Create Inclusion Strategy wizard export
// Reads from inclusion_strategy_drafts / inclusion_strategy_priorities.
// DfE order: cover, statement of intent, barriers, activity by principle,
// intended outcomes, further information (if present).
// ─────────────────────────────────────────────────────────────────────
function bodyTextOrPlaceholder(doc, y, text, placeholder = 'Not provided.') {
  if (text && text.trim()) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...DARK)
    const lines = doc.splitTextToSize(text.trim(), CW)
    for (const line of lines) {
      y = checkNewPage(doc, y, 6)
      doc.text(line, ML, y)
      y += 5
    }
  } else {
    doc.setFont('helvetica', 'italic'); doc.setFontSize(9); doc.setTextColor(...MID)
    y = checkNewPage(doc, y, 6)
    doc.text(placeholder, ML, y)
    y += 5
  }
  return y
}

function principleBarLite(doc, y, label) {
  doc.setFillColor(...LTGREY)
  doc.rect(ML, y, CW, 6, 'F')
  doc.setTextColor(...NAVY)
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.text(label, ML + 3, y + 4.5)
  return y + 6
}

export function generateInclusionStrategyDraft({ schoolName = '', draft = {}, barriers = [], priorities = [] }) {
  const doc     = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const dateStr = fmt()
  const ay      = draft.academic_year_label?.trim() || academicYear()
  const safeName = (schoolName || 'School').replace(/[^a-z0-9]/gi, '_')

  // ── Cover ─────────────────────────────────────────────────────────
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, 210, 297, 'F')

  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(schoolName || 'School', 105, 90, { align: 'center' })

  doc.setFontSize(15)
  doc.text('Inclusion Strategy', 105, 108, { align: 'center' })
  doc.setFontSize(12)
  doc.text(ay, 105, 120, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(180, 200, 220)
  let coverY = 138
  if (draft.review_date) {
    const reviewStr = new Date(draft.review_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    doc.text(`Review date: ${reviewStr}`, 105, coverY, { align: 'center' })
    coverY += 10
  }
  if (draft.authorised_by?.trim()) {
    doc.text(`Authorised by: ${draft.authorised_by.trim()}`, 105, coverY, { align: 'center' })
    coverY += 10
  }
  if (barriers.length > 0) {
    doc.setTextColor(...hexToRgb('#F4B860'))
    doc.text(`Barriers identified: ${barriers.length}`, 105, coverY, { align: 'center' })
  }

  doc.setFontSize(8)
  doc.setTextColor(120, 150, 180)
  doc.text(`Generated: ${dateStr}`, 105, 270, { align: 'center' })
  doc.text('Generated by Inclusion Dashboard · inclusiondashboard.co.uk', 105, 285, { align: 'center' })

  // ── Content pages ─────────────────────────────────────────────────
  doc.addPage()
  let y = 14

  // Statement of intent
  y = sectionBar(doc, y, 'Statement of Intent')
  y += 6
  y = bodyTextOrPlaceholder(doc, y, draft.statement_of_intent)
  y += 6

  // Barriers to learning and participation
  y = checkNewPage(doc, y, 14)
  y = sectionBar(doc, y, 'Barriers to Learning and Participation')
  y += 6
  if (barriers.length === 0) {
    doc.setFont('helvetica', 'italic'); doc.setFontSize(9); doc.setTextColor(...MID)
    doc.text('No barriers selected.', ML, y)
    y += 5
  } else {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...DARK)
    barriers.forEach((b, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${b.description}`, CW)
      y = checkNewPage(doc, y, lines.length * 5 + 2)
      doc.text(lines, ML, y)
      y += lines.length * 5 + 2
    })
  }
  y += 4

  // Activity in this academic year — grouped by principle
  y = checkNewPage(doc, y, 14)
  y = sectionBar(doc, y, 'Activity in this Academic Year')
  y += 6

  const byPrinciple = DFE_PRINCIPLES
    .map(p => ({ principle: p, items: priorities.filter(pr => pr.principle === p) }))
    .filter(g => g.items.length > 0)

  if (byPrinciple.length === 0) {
    doc.setFont('helvetica', 'italic'); doc.setFontSize(9); doc.setTextColor(...MID)
    doc.text('No priorities added.', ML, y)
    y += 5
  } else {
    for (const group of byPrinciple) {
      y = checkNewPage(doc, y, 12)
      y = principleBarLite(doc, y, group.principle)
      y += 5

      for (const item of group.items) {
        y = checkNewPage(doc, y, 14)
        doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...DARK)
        const titleLines = doc.splitTextToSize(item.point_description || 'Untitled priority', CW - 4)
        doc.text(titleLines, ML + 2, y)
        y += titleLines.length * 5

        if (item.activity_description?.trim()) {
          const actLines = doc.splitTextToSize(item.activity_description.trim(), CW - 4)
          y = checkNewPage(doc, y, actLines.length * 4.5)
          doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(...MID)
          doc.text(actLines, ML + 2, y)
          y += actLines.length * 4.5
        }

        const metaParts = []
        if (item.source_point_id) metaParts.push('From identified provision gap')
        if (item.budgeted_cost) metaParts.push(`£${Number(item.budgeted_cost).toLocaleString('en-GB')}`)
        if (item.funding_source) metaParts.push(FUNDING_LABELS[item.funding_source] ?? item.funding_source)
        if (metaParts.length > 0) {
          y = checkNewPage(doc, y, 4.5)
          doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.setTextColor(...MID)
          doc.text(metaParts.join(' · '), ML + 2, y)
          y += 4.5
        }
        y += 4
      }
      y += 3
    }
  }
  y += 2

  // Intended outcomes
  y = checkNewPage(doc, y, 14)
  y = sectionBar(doc, y, 'Intended Outcomes')
  y += 6
  y = bodyTextOrPlaceholder(doc, y, draft.intended_outcomes)

  // Further information — only if non-empty
  if (draft.further_information?.trim()) {
    y += 6
    y = checkNewPage(doc, y, 14)
    y = sectionBar(doc, y, 'Further Information')
    y += 6
    y = bodyTextOrPlaceholder(doc, y, draft.further_information)
  }

  applyHeadersFooters(doc, schoolName || 'School', `Inclusion Strategy ${ay}`)
  doc.save(`Inclusion_Strategy_${safeName}_${ay.replace('/', '-')}.pdf`)
}
